"""re-added admin

Revision ID: 4b2d9e733cae
Revises: 6a5dbd31738e
Create Date: 2023-07-07 14:53:10.045773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b2d9e733cae'
down_revision = '6a5dbd31738e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['adminID'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('houseId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'household', ['houseId'], ['id'])
        batch_op.drop_column('house_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'household', ['house_id'], ['id'])
        batch_op.drop_column('houseId')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('item_ibfk_1', 'user', ['owner_id'], ['id'])
        batch_op.drop_column('userId')

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('adminID')

    # ### end Alembic commands ###
