"""corrected user table verfied to verified

Revision ID: bd2bb237509b
Revises: 7b4f0cca89a1
Create Date: 2023-07-08 15:37:07.937236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd2bb237509b'
down_revision = '7b4f0cca89a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('verfied')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verfied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
