"""temporarily removed admin

Revision ID: f6ece7f458c9
Revises: cfb2b1e8a6b7
Create Date: 2023-07-06 19:38:23.485557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6ece7f458c9'
down_revision = 'cfb2b1e8a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.drop_index('house_name')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('house_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_name', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('house_name', ['house_name'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
